SELECT A.REGIONID,
 B.REGIONNAME,
  A.PRODUCT,
   A.YEARWEEK,
    A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B    

ON A.REGIONID = B.REGIONID

where product = 'PRODUCT4' ;


SELECT COUNT(*) FROM
(
SELECT COUNT (*)
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID
);


SELECT A.regionid *FROM
(
SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID
)
where 1=1
and regionid = 'a77';


SELECT A.REGIONID,
 B.REGIONNAME,
  A.PRODUCT,
   A.YEARWEEK,
    A.QTY

FROM KOPO_CHANNEL_SEASONALITY_NEW A
WHERE KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID


select * from KOPO_REGION_MST



